### PR TITLE
Some small cleanup work

### PR DESCRIPTION
**Pull request by jnwatts**
Fixed a few glaring issues

### CODE REVIEW

**Comment by jnwatts** [comment]
As in 1422c2f, should probably also do the same for content posts with embedded images:
```find content -type f -print0 | xargs -0 sed -i'' -re 's#(image:: *)http://#\1//#g'```

**Comment by deejoe** [comment]
I'm merging these and will try to roll these into the web site later, but ... since most of this is against the them, are you submitting them upstream as well?

**Comment by jnwatts** [comment]
Is this repo not the upstream source? That's how Alex described it to me. :-)

**Comment by deejoe** [comment]
On Tue, Mar 14, 2017 at 01:54:43PM -0700, Josh wrote:
> Is this repo not the upstream source? That's how Alex described it to me. :-)

For the specific content from Interlock Rochester the buck stops here, yes,
this is the ultimate upstream.

For the static site generation software Pelican which we are using, it
isn't.

For the Pelican theme pelican-clean-blog it isn't, either:

https://github.com/gilsondev/pelican-clean-blog

most of your very welcome patches have been against things we inherit from
the upstream theme pelican-clean-blog.

That said, they have a couple of PRs growing moldy, now a couple of months
old, so I wouldn't be in too big of a rush, but still.

I'm thinking it makes sense for us maybe to maintain our own fork of the
theme within the Interlock-Rochester github org anyway. I'm not too smrt
about what The Right Way then would be for working on that in parallel, but
it seems issuing PRs from that would be a way to integrate your changes and
try to keep upstream supplied with them, etc. while also keeping it updated
for our own use.  Or not.

**Comment by jnwatts** [comment]
Ah, yes, I see what you meant now. I'd be happy to mirror my fixes to the upstream(s) :-)

The "Right Way" AFIAK depends on how much specialization you want in your site design. Whenever I've ever used a theme, I've quickly diverged from the original author's designs to add my own features or tweak to my own preferences. I can totally understand wanting to keep with the original author's (as much as possible anyway) design though, so for that I would just recommend to keep going the way you have and send them discrete patches when possible.

**Pull request merged**
