### PR TITLE
My web page to describe creating a web page.

### PR DESCRIPTION
**Pull request by ghpt**
Trying to test the process

### CODE REVIEW

**Comment by deejoe** [comment]
I moved the file from the 'markdown' folder to the 'content' folder. I don't remember why we have both, the 'markdown' folder may be a vestige of the conversion from wp-engine files. 'content' is the Pelican convention. 

When I ran ```pelican content``` it generated this error

    ERROR: Skipping ./HDI-make-web-content.md: could not find information about 'title'

Please see

http://docs.getpelican.com/en/stable/content.html

which gives the format for file metadata like "Title:"

**Comment by ghpt** [comment]
I just used the file tape-painting.md as a template and modified it. I did
not see .md files in the content directory, only .rst files. So I did not
think that was the place for markdown. If it isn't the place to put files
we should definitely get rid of it. If content is the correct place for
markdown why aren't the files named with .md extensions?

Carl

**Comment by deejoe** [comment]
Sorry for not having gotten your posting in place yet.

To try to answer your questions and to explain:

The tool to import wordpress content into pelican generates reStructuredText
(.rst) files. That's why most of the files in content/ are .rst files,
because most of our content came through that process. Fortunately, Pelican
doesn't care if we have a mixture of .rst and of .md in there, so long as
what's .rst is actually reStructuredText and what's .md is actually
MarkDown.

I find markdown simpler to write. So, I ran the automatically generated .rst
files through pandoc to convert them to markdown. Unfortunately, this did
not convert the pelican-specific headers, leaving us with files whose bodies
are markdown, but whose headers are pelican-specific rst. 

At the point, my choices were either to write my own conversion for the
headers, or punt and use the .rst files as is, using markdown for new
content. I chose the latter. Even now, I expect, one could write new content
in rst and Pelican would be fine with that. Pick your poison.

I remembered none of this when we were first working on this last night and
have only pieced it together since then by looking at the directory and at
the commit log.

So, sorry also for not having cleared out the markdown/ directory earlier.
I've done that now, though.

The content/ directory *does* contain a few markdown files, specifically,
most anything that's been written since the move. There aren't many, but
hopefully we can increase the population of them through exercises like
this.

**Comment by deejoe** [comment]
OK, this page has now been incorporated, with some edits. 

If you want to pull this down and compare, that'd be good.  If you have corrections or changes, please let me know, via PR or sending a patch or diff or whatever. Thanks!

**Pull request closed without merging**
